version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: donyscode
      POSTGRES_PASSWORD: EndpointEasy
      POSTGRES_DB: endpointizer_db
    ports:
      - '5499:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
